language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build-storybook"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build-storybook
  on:
    branch: master
